apiVersion: v1
kind: ServiceAccount
metadata:
  name: spark-client-sa
  namespace: backtest-crypto
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: backtest-crypto
  name: spark-client-role
rules:
- apiGroups: [""]
  resources: ["configmaps", "pods", "pods/log", "pods/status", "services"]
  verbs: ["*"]
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses", "ingresses/status"]
  verbs: ["*"]
- apiGroups: ["sparkoperator.k8s.io"]
  resources: [sparkapplications]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: spark-client-role-binding
  namespace: backtest-crypto
subjects:
- kind: ServiceAccount
  name: spark-client-sa
  namespace: backtest-crypto
roleRef:
  kind: Role
  name: spark-client-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: node-reader
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: spark-client-cluster-role-binding
subjects:
- kind: ServiceAccount
  name: spark-client-sa
  namespace: backtest-crypto
roleRef:
  kind: ClusterRole
  name: node-reader
  apiGroup: rbac.authorization.k8s.io
